spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profile: dev
  application:
    name: config-client-dev
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name:  config-client-test